### ISSUE TITLE
USER STORY Request poll

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/My-First-Agile-Project#7]
In order to **run desirable trails** as a **user**, I can **put my request on a poll**

# Acceptance Criteria
- No swearing is allowed
- Time, date and location is required

# Tasks

- [ ] Add value errors for all known undesired swear words
- [ ] Add HTML and CSS to the poll
- [ ] Add javascript to change the amount of upvotes when a user chooses votes an option
