### ISSUE TITLE
USER STORY make poll

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/My-First-Agile-Project#8]
In order to **find out what runners want to run** as a **admin**, I can **create a poll for users to add their requests to**

# Acceptance Criteria
- Needs to display amount of upvotes
- Need to be easily accessible on the website

# Tasks

- [ ] Implement HTML and CSS in an advertising manner to express its availability on the website
- [ ] Add it as a pop up of sorts on each page the user is on.
- [ ] Add a python code to keep an update on the amount of upvotes of each option, making the onw with the highest upvotes at the top and so and so.
